src/Web/Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using CodeMooc.Web.Data;
using CodeMooc.Web.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RestSharp;

namespace CodeMooc.Web.Controllers {

    [Route("iscrizione")]
    public class RegisterController : Controller {

        protected DataContext Database { get; }
        protected ILogger<RegisterController> Logger { get; }

        public RegisterController(
            DataContext database,
            ILogger<RegisterController> logger
        ) {
            Database = database;
            Logger = logger;
        }

        private async Task SendConfirmationEmail(Data.Registration user, Data.Email email) {
            string url = Url.Action(nameof(Validate), "Register", new { id = user.Id, secret = user.ConfirmationSecret });
            string link = Environment.GetEnvironmentVariable("BASE_URL") + url;

            Logger.LogTrace(LoggingEvents.Email, "Destination URL {0}, final link {1}", url, link);

            using (var client = new SmtpClient()) {
                var credentials = new NetworkCredential(
                    Environment.GetEnvironmentVariable("SMTP_USERNAME"),
                    Environment.GetEnvironmentVariable("SMTP_PASSWORD")
                );

                client.EnableSsl = true;
                client.Host = Environment.GetEnvironmentVariable("SMTP_HOST");
                client.Port = Convert.ToInt32(Environment.GetEnvironmentVariable("SMTP_PORT"));
                client.Credentials = credentials;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.Timeout = 5000;

                Logger.LogTrace(LoggingEvents.Email, "SMTP host {0}:{1} username {2} SSL {3}", client.Host, client.Port, credentials.UserName, client.EnableSsl);

                var noReplyAddress = new MailAddress(Environment.GetEnvironmentVariable("MAIL_FROM"), "CodeMOOC.net");
                var msg = new MailMessage {
                    From = noReplyAddress,
                    Subject = "Verifica indirizzo e-mail",
                    IsBodyHtml = false,
                    Body = $"Ciao {user.Name} {user.Surname}!\n\nGrazie per esserti registrato/a su CodeMOOC.net. Ti preghiamo di verificare il tuo indirizzo e-mail cliccando sul seguente link:\n{link}\n\nA presto!\nCodeMOOC.net"
                };
                msg.To.Add(new MailAddress(email.Address, $"{user.Name} {user.Surname}"));
                if (!string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("CONFIRMATION_MAIL_BCC"))) {
                    msg.Bcc.Add(Environment.GetEnvironmentVariable("CONFIRMATION_MAIL_BCC"));
                }
                msg.ReplyToList.Add(noReplyAddress);

                Logger.LogTrace(LoggingEvents.Email, "Sending e-mail");

                try {
                    await client.SendMailAsync(msg);
                }
                catch (Exception ex) {
                    Logger.LogError(LoggingEvents.Email, ex, "Failed to send e-mail");
                }

                Logger.LogDebug(LoggingEvents.Email, "E-mail sent");
            }
        }

        [HttpGet]
        public IActionResult Index() {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Process(RegistrationViewModel model, [FromForm(Name = "g-recaptcha-response")] string recaptchaResponse) {
            Logger.LogInformation(LoggingEvents.Registration, "Received registration request");

            // Check e-mail
            if (!string.IsNullOrWhiteSpace(model.Email)) {
                var existingMailUser = (from e in Database.Emails
                                        where e.Address == model.Email.ToLowerInvariant()
                                        select e).SingleOrDefault();
                if (existingMailUser != null) {
                    Logger.LogInformation(LoggingEvents.Registration, "E-mail already registered");
                    ModelState.AddModelError(nameof(RegistrationViewModel.Email), "Indirizzo e-mail già registrato");
                }
            }

            // Check fiscal code
            if (!string.IsNullOrWhiteSpace(model.FiscalCode)) {
                var existingCodeUser = (from r in Database.Registrations
                                        where r.FiscalCode == model.FiscalCode.ToUpperInvariant()
                                        where r.ConfirmationTimestamp != null
                                        select r).SingleOrDefault();
                if (existingCodeUser != null) {
                    Logger.LogInformation(LoggingEvents.Registration, "Fiscal code already registered");
                    ModelState.AddModelError(nameof(RegistrationViewModel.FiscalCode), "Codice fiscale già registrato");
                }
            }

            // Check birthday
            if (!DateTime.TryParseExact(model.Birthday, "dd-MM-yyyy", new CultureInfo("it-IT"), DateTimeStyles.AssumeLocal, out var birthday)) {
                Logger.LogInformation(LoggingEvents.Registration, "Birthday {0} not valid", model.Birthday);
                ModelState.AddModelError(nameof(RegistrationViewModel.Birthday), "Inserire data di nascita nel formato GG-MM-AAAA");
            }

            // Check ReCaptcha
            Logger.LogTrace(LoggingEvents.Registration, "Checking ReCaptcha token");
            var rest = new RestClient("https://www.google.com/recaptcha/api/siteverify");
            var restReq = new RestRequest(Method.POST);
            restReq.AddParameter("response", recaptchaResponse);
            restReq.AddParameter("secret", Environment.GetEnvironmentVariable("GOOGLE_RECAPTCHA_SECRET"));
            var recaptchaResult = rest.Execute<ReCaptchaResponse>(restReq);
            if (!recaptchaResult.IsSuccessful || !recaptchaResult.Data.Success) {
                Logger.LogInformation(LoggingEvents.Registration, "ReCaptcha verification failed");
                ModelState.AddModelError("ReCaptcha", "Attiva il controllo anti-spam ReCaptcha");

                return View("Create", model);
            }
            Logger.LogDebug(LoggingEvents.Registration, "ReCaptcha verification succeeded for hostname {0}", recaptchaResult.Data.Hostname);

            // Final validity check
            if (!ModelState.IsValid) {
                Logger.LogDebug(LoggingEvents.Registration, "Model binding failed");

                return View("Create", model);
            }

            Logger.LogDebug("Input validated, proceeding with registration");
            var hashedPassword = BCrypt.Net.BCrypt.EnhancedHashPassword(model.Password);

            var user = new Data.Registration {
                Name = model.Name.Trim(),
                Surname = model.Surname.Trim(),
                Birthday = birthday.Date,
                Birthplace = model.Birthplace,
                FiscalCode = model.FiscalCode.ToUpperInvariant(),
                AddressStreet = model.AddressStreet,
                AddressCity = model.AddressCity,
                AddressCap = model.AddressCap,
                AddressCountry = model.AddressCountry,
                PasswordSchema = "bcrypt.net", // hard-coded to hash function
                PasswordHash = hashedPassword,
                Category = model.Category,
                HasAttendedMooc = model.HasAttendedMooc,
                HasCompletedMooc = model.HasCompletedMooc,
                RegistrationTimestamp = DateTime.UtcNow,
                ConfirmationSecret = Startup.GenerateSecret()
            };
            Database.Registrations.Add(user);

            var email = new Data.Email {
                Address = model.Email.Trim().ToLowerInvariant(),
                IsPrimary = true,
                AssociationTimestamp = user.RegistrationTimestamp,
                Registration = user
            };
            Database.Emails.Add(email);

            int changes = Database.SaveChanges();
            if(changes != 2) {
                throw new InvalidOperationException("Expected changes equal to 2 when registering user");
            }

            await SendConfirmationEmail(user, email);

            // Confirmation view
            ViewData["email"] = email.Address;
            return View("Confirm");
        }

        [HttpGet("verifica/{id}")]
        public IActionResult Validate([FromRoute] int id, [FromQuery] string secret) {
            var user = (from r in Database.Registrations
                        where r.Id == id
                        select r).SingleOrDefault();

            if (user == null) {
                Logger.LogInformation(LoggingEvents.Verification, "User #{0} not found", id);
                return StatusCode(404);
            }

            if (user.ConfirmationTimestamp != null) {
                Logger.LogDebug(LoggingEvents.Verification, "User {0} verified", id);
                return View("Validated");
            }

            if (!user.ConfirmationSecret.Equals(secret, StringComparison.InvariantCulture)) {
                Logger.LogInformation(LoggingEvents.Verification, "Secrets do not match {0} != {1}", secret, user.ConfirmationSecret);
                return StatusCode(404);
            }

            Logger.LogDebug(LoggingEvents.Verification, "Returning verification page for user {0}", id);

            ViewData["id"] = id;
            ViewData["secret"] = secret;
            return View("Validate");
        }

        [HttpPost("verifica/{id}")]
        public IActionResult DoValidate([FromRoute] int id, [FromForm] string secret) {
            var user = (from r in Database.Registrations
                        where r.Id == id
                        where r.ConfirmationTimestamp == null
                        select r).SingleOrDefault();

            if (user == null) {

src/Web/Web/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CodeMooc.Web.Controllers {

    [Route("")]
    public class StaticController : Controller {

        protected ILogger<StaticController> Logger { get; }

        public StaticController(
            ILogger<StaticController> logger
        ) {
            Logger = logger;
        }

        [HttpGet]
        public IActionResult ShowFront() {
            return View("Front");
        }

        [HttpGet("statuto")]
        public IActionResult ShowStatute() {
            return View("Statute");
        }

    }

}

src/Web/Web/Views/Register/Confirm.cshtml
@{
    Layout = "Main";
    ViewData["Title"] = "Iscrizione effettuata";
}

<div class="container">
    <h1 class="text-center">Iscrizione effettuata</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <p>Grazie per esserti iscritto/a su <b>CodeMOOC.net</b>!</p>

        <p>Ti stiamo inviando un’e-mail all'indirizzo @ViewData["email"] con un collegamento per confermare la validità del tuo indirizzo e-mail. (Controlla anche nella cartella dello spam se non dovessi ricevere niente entro un paio di minuti.)</p>
    </div>
</div>

src/Web/Web/Views/Register/Create.cshtml
@{
    Layout = "Main";
    ViewData["Title"] = "Iscrizione";
}
@model CodeMooc.Web.Model.RegistrationViewModel

<div class="container">
    <h1 class="text-center">Iscrizione</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <p>
            <b>CodeMOOC</b> è l’acronimo di un corso online aperto e gratuito che l’Università di Urbino eroga dal&nbsp;2016 per aiutare gli insegnanti ad introdurre il pensiero computazionale in classe attraverso la pratica del coding . CodeMOOC ha creato un modo nuovo di fare formazione, ha aperto un collegamento diretto tra università e scuola, ha offerto nuovi strumenti di cambiamento dal basso, ha favorito l’innovazione partendo dalle competenze, ha dato vita ad una comunità di apprendimento e di pratica che ad oggi coinvolge più di 30.000&nbsp;insegnanti e, per loro tramite, più di un milione di ragazzi.
        </p>
        
        <p>
            <b>CODEMOOC NET</b> nasce per riconoscere l’identità e il valore di questa comunità di pratica, per offrirle strumenti adeguati di confronto, di condivisione e di crescita, per ampliarne l’impatto sociale e culturale, per permetterle di autofinanziare lo sviluppo di strumenti e progetti utili a perseguirne le finalità. Tra questi: una rete di insegnanti con competenze ed esperienze certificate di coding a scuola, che possano essere facilmente rintracciate e messe a disposizione delle scuole che ne avvertano il bisogno, una rivista tematica open access che offra agli insegnanti che praticano il coding a scuola l’opportunità di documentare in modo rigoroso e condividere le proprie esperienze in forma di lesson plan, revisionati tra pari e validati da un comitato editoriale e da un comitato scientifico.
        </p>

        <p>
            <b>CODEMOOC NET</b> è un’Assocazione di Promozione Sociale e Culturale senza scopo di lucro, aperta alla partecipazione di chiunque ne riconosca lo scopo e lo spirito.
        </p>

        <form asp-controller="Register" asp-action="Process" method="post" class="form-horizontal" role="form" asp-antiforgery="false">

            <h2>Anagrafica</h2>

            <div class="form-row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Name">Nome *</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Surname">Cognome *</label>
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname"></span>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Birthday">Data di nascita *</label>
                        <input asp-for="Birthday" class="form-control" pattern="[0-9]{2}-[0-9]{2}-[0-9]{4}" />
                        <span asp-validation-for="Birthday"></span>
                        <small>Specificare la data nel formato GG-MM-AAAA (giorno, mese e anno, separati da un trattino).</small>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Birthplace">Luogo di nascita *</label>
                        <input asp-for="Birthplace" class="form-control" />
                        <span asp-validation-for="Birthplace"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="FiscalCode">Codice fiscale *</label>
                <input asp-for="FiscalCode" class="form-control" />
                <span asp-validation-for="FiscalCode"></span>
            </div>

            <div class="form-group">
                <label asp-for="AddressStreet">Indirizzo *</label>
                <input asp-for="AddressStreet" class="form-control" />
                <span asp-validation-for="AddressStreet"></span>
            </div>

            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="AddressCap">CAP *</label>
                        <input asp-for="AddressCap" class="form-control" />
                        <span asp-validation-for="AddressCap"></span>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label asp-for="AddressCity">Città *</label>
                        <input asp-for="AddressCity" class="form-control" />
                        <span asp-validation-for="AddressCity"></span>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="AddressCountry">Paese *</label>
                <input asp-for="AddressCountry" class="form-control" />
                <span asp-validation-for="AddressCountry"></span>
            </div>

            <hr />

            <h2>Dati di accesso</h2>

            <div class="form-group">
                <label asp-for="Email">Indirizzo e-mail *</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email"></span>
                <small class="text-muted">
                    Se stai già partecipando (o intendi partecipare) al <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">crowdfunding di CodeMOOC.net</a>, assicurati di iscriverti utilizzando lo stesso indirizzo e-mail.
                </small>
            </div>

            <div class="form-group">
                <label asp-for="Password">Password *</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"></span>
            </div>

            <div class="form-group">
                <label asp-for="PasswordConfirm">Conferma Password *</label>
                <input asp-for="PasswordConfirm" class="form-control" />
                <span asp-validation-for="PasswordConfirm"></span>
            </div>

            <hr />

            <h2>Informazioni aggiuntive</h2>

            <div class="form-group">
                <label asp-for="Category">Categoria</label>
                <select asp-for="Category" asp-items="Html.GetEnumSelectList<CodeMooc.Web.UserCategory>()" class="form-control"></select>
                <span asp-validation-for="Category"></span>
            </div>

            <div class="form-check">
                <input asp-for="HasAttendedMooc" class="form-check-input" />
                <label asp-for="HasAttendedMooc" class="form-check-label">Spunta questa casella se hai frequentato <b>CodeMOOC</b> o altri MOOC sul coding dell’Università di Urbino.</label>
            </div>

            <div class="form-check">
                <input asp-for="HasCompletedMooc" class="form-check-input" />
                <label asp-for="HasCompletedMooc" class="form-check-label">Spunta questa casella se hai concluso <b>CodeMOOC</b> o altri MOOC sul coding dell’Università di Urbino.</label>
            </div>

            <hr />

            <div class="form-check">
                <input asp-for="AcceptsStatute" class="form-check-input" />
                <label asp-for="AcceptsStatute" class="form-check-label">Dichiaro di aver preso visione dello <a href="@Url.Action("ShowStatute", "Static")">Statuto</a> e mi impegno a rispettarlo.</label>
                <span asp-validation-for="AcceptsStatute"></span>
            </div>

            <div class="form-check">
                <input asp-for="AcceptsManifesto" class="form-check-input" />
                <label asp-for="AcceptsManifesto" class="form-check-label">Dichiaro di impegnarmi a rispettare il <a href="http://paroleostili.com/manifesto/">Decalogo del Manifesto della Comunicazione non Ostile</a>.</label>
                <span asp-validation-for="AcceptsManifesto"></span>
            </div>

            <div class="form-check">
                <input asp-for="AcceptsProcess" class="form-check-input" />
                <label asp-for="AcceptsProcess" class="form-check-label">Dichiaro di essere consapevole che la domanda di iscrizione verrà presa in carico solo dopo la conferma dell’indirizzo e-mail fornito, e che l’effettiva iscrizione avverrà a seguito della verifica del versamento di un contributo non inferiore ai 20&nbsp;Euro a beneficio del <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">progetto CODEMOOC&nbsp;NET</a>, effettuato specificando lo stesso indirizzo e-mail.</label>
                <span asp-validation-for="AcceptsProcess"></span>
            </div>

            <div class="form-check">
                <input asp-for="AcceptsPrivacy" class="form-check-input" />
                <label asp-for="AcceptsPrivacy" class="form-check-label">Dichiaro di aver preso visione dell’<a href="~/informativa-privacy-codemooc-net.pdf">informativa sulla privacy</a>.</label>
                <span asp-validation-for="AcceptsPrivacy"></span>
            </div>

            <p>Alla luce dell’informativa ricevuta:</p>

            <div class="form-check">
                <input asp-for="AcceptsTreatment" class="form-check-input" />
                <label asp-for="AcceptsTreatment" class="form-check-label">Esprimo il consenso al trattamento dei miei dati personali inclusi quelli considerati come categorie particolari di dati,</label>
                <span asp-validation-for="AcceptsTreatment"></span>
            </div>

            <div class="form-check">
                <input asp-for="AcceptsCommunication" class="form-check-input" />
                <label asp-for="AcceptsCommunication" class="form-check-label">Esprimo il consenso alla comunicazione dei miei dati personali per le finalità indicate nell’informativa.</label>
                <span asp-validation-for="AcceptsCommunication"></span>
            </div>

            <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LccN4cUAAAAAHkPVCGZLem-g6wo5b33InjSb6Ja" data-theme="dark"></div>
                @Html.ValidationMessage("ReCaptcha")
            </div>

            <button id="submit" type="submit" value="submit" class="btn btn-primary btn-block">Iscriviti!</button>
        </form>
    </div>

</div>

src/Web/Web/Views/Register/Validate.cshtml
@{
    Layout = "Main";
    ViewData["Title"] = "Conferma iscrizione";
}

<div class="container">
    <h1 class="text-center">Conferma iscrizione</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <p>Clicca il pulsante qui sotto per confermare la tua iscrizione a <b>CodeMOOC.net</b>:</p>

        <form asp-action="DoValidate" asp-controller="Register" asp-route-id="@ViewData["id"]" asp-antiforgery="false" method="post" class="form-horizontal" role="form">
            <input type="hidden" name="secret" value="@ViewData["secret"]" />
            <button id="submit" type="submit" value="submit" class="btn btn-primary btn-block">Conferma!</button>
        </form>
    </div>
</div>

src/Web/Web/Views/Register/Validated.cshtml
@{
    Layout = "Main";
    ViewData["Title"] = "Iscrizione confermata";
}

<div class="container">
    <h1 class="text-center">Iscrizione confermata</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <p>Il tuo indirizzo e-mail è stato verificato e la tua registrazione è ora confermata.</p>
        <p>Benvenuto/a a bordo!</p>
    </div>
</div>