src/Web/Web/Controllers/BadgeController.cs
using System;
using System.Linq;
using CodeMooc.Web.Data;
using CodeMooc.Web.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CodeMooc.Web.Controllers {

    [Route("badge")]
    [AllowAnonymous]
    public class BadgeController : Controller {

        protected DataContext Database { get; }
        protected ILogger<BadgeController> Logger { get; }

        public BadgeController(
            DataContext database,
            ILogger<BadgeController> logger
        ) {
            Database = database;
            Logger = logger;
        }

        public const int MinYear = 2019;
        public const int MaxYear = 2021;

        [HttpGet("{type}/criteri")]
        public IActionResult ShowCriteria([FromRoute] string type) {
            Logger.LogDebug(LoggingEvents.Badges, "Loading criteria for badge type {0}", type);

            if(!type.TryParseLegacyBadgeType(out BadgeType badgeType)) {
                return NotFound();
            }

            return View("Criteria", new BadgeCriteriaViewModel {
                BadgeType = badgeType,
                Year = 2019
            });
        }

        [HttpGet("{type}/{year}/criteri")]
        public IActionResult ShowCriteriaYear([FromRoute] string type, [FromRoute] int year) {
            Logger.LogDebug(LoggingEvents.Badges, "Loading criteria for badge type {0} year {1}", type, year);

            if(!type.TryParseBadgeType(out BadgeType badgeType)) {
                return NotFound();
            }

            if(year < MinYear || year > MaxYear) {
                return NotFound();
            }

            return View("Criteria", new BadgeCriteriaViewModel {
                BadgeType = badgeType,
                Year = year
            });
        }

        [HttpGet("{type}/evidence/{token}")]
        public IActionResult ShowEvidence([FromRoute] string type, [FromRoute] string token) {
            Logger.LogDebug(LoggingEvents.Badges, "Loading evidence for badge type {0}", type);

            if (!type.TryParseLegacyBadgeType(out BadgeType badgeType)) {
                return NotFound();
            }

            return ShowEvidenceInternal(badgeType, 2019, token);
        }

        [HttpGet("{type}/{year}/evidence/{token}")]
        public IActionResult ShowEvidenceYear([FromRoute] string type, [FromRoute] int year, [FromRoute] string token) {
            Logger.LogDebug(LoggingEvents.Badges, "Loading evidence for badge type {0} year {1}", type, year);

            if(!type.TryParseBadgeType(out BadgeType badgeType)) {
                return NotFound();
            }

            if(year < MinYear || year > MaxYear) {
                return NotFound();
            }

            return ShowEvidenceInternal(badgeType, year, token);
        }

        protected IActionResult ShowEvidenceInternal(BadgeType badgeType, int year, string token) {
            var badge = (from b in Database.Badges
                         where b.Type == badgeType
                         where b.Year == new DateTime(year, 1, 1)
                         where b.EvidenceToken == token
                         select b).SingleOrDefault();
            if(badge == null) {
                Logger.LogDebug(LoggingEvents.Badges, "Badge of type {0} year {1} and token '{2}' not found", badgeType, year, token);
                return NotFound();
            }

            var user = (from u in Database.Donations
                        where u.Email == badge.Email
                        where u.Year == new DateTime(year, 1, 1)
                        select u).FirstOrDefault();
            if(user == null) {
                Logger.LogError(LoggingEvents.Badges, "Donation for badge email {0} not found", badge.Email);
                return NotFound();
            }

            return View("Evidence", new BadgeEvidenceViewModel {
                Name = user.Name,
                Surname = user.Surname,
                Email = user.Email,
                BadgeType = badge.Type,
                Year = year,
                IssueTimestamp = badge.IssueTimestamp
            });
        }

    }

}

src/Web/Web/Controllers/DashboardController.cs
using System;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CodeMooc.Web.Data;
using CodeMooc.Web.InputModel;
using CodeMooc.Web.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace CodeMooc.Web.Controllers {

    [Route("dashboard")]
    [Authorize(Policy = Startup.MembersOnlyPolicyName)]
    public class DashboardController : Controller {

        protected readonly DataContext Database;
        protected readonly ILogger<DashboardController> Logger;
        protected readonly IConfiguration Configuration;

        public DashboardController(
            DataContext database,
            ILogger<DashboardController> logger,
            IConfiguration configuration
        ) {
            Database = database;
            Logger = logger;
            Configuration = configuration;
        }

        protected int? GetUserId() {
            if(!HttpContext.User.Identity.IsAuthenticated) {
                Logger.LogError("User not authenticated on dashboard");
                return null;
            }

            var sId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if(!int.TryParse(sId, out int id)) {
                Logger.LogError("Cannot parse user ID '{0}'", sId);
                return null;
            }

            return id;
        }

        protected T GetViewModel<T>()
            where T : DashboardBaseViewModel {

            T model = TempData.Get<T>() ?? (T)Activator.CreateInstance(typeof(T));

            var userId = GetUserId();
            if(!userId.HasValue) {
                return null;
            }

            model.LoggedUser = (from r in Database.Registrations
                                where r.Id == userId.Value
                                select r).SingleOrDefault();
            Logger.LogDebug("Loaded user information for user {0} {1}", model.LoggedUser.Id, model.LoggedUser.Name);

            return model;
        }

        public IActionResult Index() {
            var model = GetViewModel<DashboardIndexViewModel>();
            if(model == null) {
                return Forbid();
            }

            var pathProfile = GetProfilePicPath(model.LoggedUser.Id);
            model.ProfilePictureFilename = System.IO.File.Exists(pathProfile) ? Path.GetFileName(pathProfile) : null;

            return View(model);
        }

        [HttpGet("donazioni")]
        public IActionResult ShowDonations() {
            var model = GetViewModel<DashboardDonationsViewModel>();
            if(model == null) {
                return Forbid();
            }

            var emails = (from e in Database.Emails
                          where e.RegistrationId == model.LoggedUser.Id
                          select e)
                          .Include(e => e.AssociatedDonations)
                          .ToList();
            model.Donations = emails.SelectMany(e => e.AssociatedDonations).ToList();

            return View("Donations", model);
        }

        [HttpGet("stato")]
        public IActionResult ShowAssociationStatus() {
            var model = GetViewModel<DashboardStatusViewModel>();
            if(model == null) {
                return Forbid();
            }

            model.IsRegistrationConfirmed = model.LoggedUser.ConfirmationTimestamp.HasValue;

            var emails = (from e in Database.Emails
                          where e.RegistrationId == model.LoggedUser.Id
                          select e)
                          .Include(e => e.AssociatedBadges)
                          .ToList();

            model.Emails = emails;
            model.PrimaryEmail = emails.Where(e => e.IsPrimary).Single();

            model.Badges = emails.SelectMany(e => e.AssociatedBadges).ToList();

            model.IsAssociateForCurrentYear = model.Badges.Any(b => b.Year.Year == DateTime.Now.Year && b.Type == BadgeType.Member);

            model.ConfirmationEmailAddress = Environment.GetEnvironmentVariable("CONFIRMATION_MAIL_BCC");

            return View("Status", model);
        }

        protected string GetCurriculumPath(int userId) {
            var pathsConf = Configuration.GetSection("Paths");
            string pathCurricula = pathsConf["Curricula"];

            return Path.Combine(pathCurricula, $"{userId}.pdf");
        }

        protected string GetProfilePicPath(int userId) {
            var pathsConf = Configuration.GetSection("Paths");            
            string pathProfilePics = pathsConf["ProfilePics"];

            return Path.Combine(pathProfilePics, $"{userId}.jpg");
        }

        [HttpGet("curriculum")]
        public IActionResult ShowCvUpload() {
            var model = GetViewModel<DashboardUploadViewModel>();
            var userId = model.LoggedUser.Id;

            var emails = (from e in Database.Emails
                          where e.RegistrationId == userId
                          select e)
                          .Include(e => e.AssociatedBadges)
                          .ToList();
            var badges = emails.SelectMany(e => e.AssociatedBadges).ToList();
            model.IsAssociateForCurrentYear = badges.Any(b => b.Year.Year == DateTime.Now.Year && b.Type == BadgeType.Member);

            var pathProfile = GetProfilePicPath(userId);
            model.ProfilePictureFilename = System.IO.File.Exists(pathProfile) ? Path.GetFileName(pathProfile) : null;
            Logger.LogDebug("Path {0} exists {1}", pathProfile, model.ProfilePictureFilename != null);

            var pathCurriculum = GetCurriculumPath(userId);
            model.CurriculumFilename = System.IO.File.Exists(pathCurriculum) ? Path.GetFileName(pathCurriculum) : null;
            Logger.LogDebug("Path {0} exists {1}", pathCurriculum, model.ProfilePictureFilename != null);

            return View("Upload", model);
        }

        [HttpPost("curriculum")]
        public async Task<IActionResult> ProcessCvUpload(IFormFile profilePic, IFormFile curriculum) {
            var userId = GetUserId();
            if(!userId.HasValue) {
                return RedirectToAction(nameof(ShowCvUpload));
            }

            if(profilePic != null) {
                ProcessProfilePicture(userId.Value, profilePic);
            }
            if(curriculum != null) {
                await ProcessCurriculum(userId.Value, curriculum);
            }

            return RedirectToAction(nameof(ShowCvUpload));
        }

        protected void ProcessProfilePicture(int userId, IFormFile file) {
            Logger.LogDebug("Processing profile picture, name {0} size {1}", file.FileName, file.Length);

            var pathProfile = GetProfilePicPath(userId);
            using(var source = file.OpenReadStream()) {
                using(var img = Image.Load(source)) {
                    Logger.LogTrace("Resizing input image");
                    img.Mutate(x => x
                        .AutoOrient()
                        .Resize(new ResizeOptions {
                            Mode = ResizeMode.Crop,
                            Size = new SixLabors.Primitives.Size(640, 640)
                        })
                    );

                    using(var output = new FileStream(pathProfile, FileMode.Create, FileAccess.Write)) {
                        Logger.LogTrace("Writing file to {0}", pathProfile);
                        img.SaveAsJpeg(output);
                    }
                }
            }

            Logger.LogInformation("Profile picture for user {0} uploaded to {1}", userId, pathProfile);
        }

        protected async Task ProcessCurriculum(int userId, IFormFile file) {
            Logger.LogDebug("Processing curriculum, name {0} size {1}", file.FileName, file.Length);

            if(Path.GetExtension(file.FileName).Equals("pdf", StringComparison.InvariantCultureIgnoreCase)) {
                Logger.LogError("File extension is not PDF");
                TempData.Put(new DashboardUploadViewModel {
                    CurriculumFailure = DashboardUploadViewModel.CurriculumUploadFailure.WrongExtension
                });
                return;
            }

            var pathCurriculum = GetCurriculumPath(userId);
            using(var output = new FileStream(pathCurriculum, FileMode.Create, FileAccess.Write)) {
                Logger.LogTrace("Writing file to {0}", pathCurriculum);
                await file.CopyToAsync(output);
            }

            Logger.LogInformation("Curriculum for user {0} uploaded to {1}", userId, pathCurriculum);
        }

        [HttpGet("pigna-registration")]
        public async Task<IActionResult> ShowPignaNotebooksRegistration() {
            var userId = GetUserId();
            if(!userId.HasValue) {
                return NotFound();
            }

            var emails = await (from e in Database.Emails
                                where e.RegistrationId == userId.Value
                                select e)
                               .Include(e => e.AssociatedBadges)
                               .ToListAsync();
            var badges = emails.SelectMany(e => e.AssociatedBadges).ToList();
            var isAssociate = badges.Any(b => b.Year.Year == DateTime.Now.Year && b.Type == BadgeType.Member);
            if(!isAssociate) {
                return View("AssociatesOnly");
            }

            var registration = await (from reg in Database.PignaNotebookRegistrations
                                      where reg.RegistrationId == userId.Value
                                      select reg).SingleOrDefaultAsync();
            if(registration != null && registration.IsPersonalAddressComplete()) {

src/Web/Web/Views/Dashboard/AssociatesOnly.cshtml
@using CodeMooc.Web.Model
@{
    Layout = "Main";
    ViewData["Title"] = "Funzione riservata";
}

<div class="container">
    <h1 class="text-center">Funzione riservata</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        <p>◀&nbsp;@Html.ActionLink("Torna al pannello di controllo", "Index")</p>

        <div class="form-error">
            Questo modulo è disponibile soltanto per soci dell'associazione CodeMOOC.
            Unisciti alla <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">campagna di crowdfunding</a> per diventare socio.
        </div>

    </div>

</div>

src/Web/Web/Views/Dashboard/Donations.cshtml
@using CodeMooc.Web.Model
@model DashboardDonationsViewModel
@{
    Layout = "Main";
    ViewData["Title"] = "Donazioni";
}

<div class="container">
    <h1 class="text-center">Donazioni</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        <p>◀&nbsp;@Html.ActionLink("Torna al pannello di controllo", "Index")</p>

        <p>Qui di seguito sono elencate le donazioni che sono state registrate a tuo nome tramite la <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">campagna di crowdfunding</a>.</p>

        @if (Model.Donations.Count == 0) {
            <p><i>Nessuna donazione registrata a tuo nome.</i></p>
        }
        else {
            <ul>
                @foreach (var donation in Model.Donations) {
                    <li>
                        Donazione da parte di @donation.Name @donation.Surname (@donation.Email): <b>@donation.Amount&nbsp;€</b> per l’anno <b>@donation.Year.Year</b>.
                    </li>
                }
            </ul>
        }

        <p>
            <i>Nota:</i> sono richieste fino a 24&nbsp;ore perché le donazioni vengano registrate dal servizio.
        </p>

    </div>

</div>

src/Web/Web/Views/Dashboard/Index.cshtml
@using CodeMooc.Web.Model
@model DashboardIndexViewModel
@{
    Layout = "Main";
    ViewData["Title"] = "Pannello soci";
}

<div class="container">
    <h1 class="text-center">Pannello soci</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        @if (Model.ProfilePictureFilename != null) {
            <p class="text-center">
                <img src="~/uploads/profiles/@Model.ProfilePictureFilename" alt="Profilo utente" class="avatar img-fluid" />
            </p>
        }

        <p>Ciao @Model.LoggedUser.Name!</p>

        <dl>
            <dt>@Html.ActionLink("Vedi donazioni", "ShowDonations")</dt>
            <dd>Vedi le donazioni che sono state registrate a tuo nome.</dd>

            <dt>@Html.ActionLink("Vedi stato socio", "ShowAssociationStatus")</dt>
            <dd>Verifica la tua registrazione come socio dell'associazione CodeMOOC.net ed i badge rilasciati.</dd>

            <dt>@Html.ActionLink("Raccolta curricula", "ShowCvUpload")</dt>
            <dd>
                Partecipa alla rete di competenze ed esperienze che l'associazione sta costruendo, caricando il tuo curriculum.<br />
                <i>(Funzione riservata ai soci dell'associazione.)</i>
            </dd>

            <dt>@Html.ActionLink("Registrazione test quaderni Pigna", "ShowPignaNotebooksRegistration")</dt>
            <dd>
                Partecipa al test dei <b>Quaderni Pigna</b> e registrati per ottenere gratuitamente dei campioni dei quaderni e accesso all’applicazione dedicata.<br />
                <i>(Funzione riservata ai soci dell'associazione.)</i>
            </dd>
        </dl>

    </div>

</div>

src/Web/Web/Views/Dashboard/PignaRegistration.cshtml
@model CodeMooc.Web.InputModel.PignaRegistrationInputModel
@{
    Layout = "Main";
    ViewData["Title"] = "Registrazione Pigna";
}

<div class="container">
    <h1 class="text-center">Registrazione Pigna</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <p>
            Compilando questo modulo puoi registrarti per ricevere in anteprima dei campioni dei <b>Quaderni Pigna</b> e accesso alla relativa applicazione mobile.
        </p>

        <form asp-controller="Dashboard" asp-action="ProcessPignaNotebooksRegistration" method="post" class="form-horizontal" role="form" asp-antiforgery="false">

            @Html.ValidationSummary(true)

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="MeccanographicCode" class="control-label"></label>
                <input asp-for="MeccanographicCode" class="form-control" />
                <span asp-validation-for="MeccanographicCode" class="text-danger"></span>
            </div>

            <h3>Indirizzo della scuola</h3>

            <div class="form-group">
                <label asp-for="SchoolName" class="control-label"></label>
                <input asp-for="SchoolName" class="form-control" />
                <span asp-validation-for="SchoolName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SchoolAddress" class="control-label"></label>
                <input asp-for="SchoolAddress" class="form-control" />
                <span asp-validation-for="SchoolAddress" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="SchoolCap" class="control-label"></label>
                        <input asp-for="SchoolCap" class="form-control" />
                        <span asp-validation-for="SchoolCap" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="form-group">
                        <label asp-for="SchoolCity" class="control-label"></label>
                        <input asp-for="SchoolCity" class="form-control" />
                        <span asp-validation-for="SchoolCity" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label asp-for="SchoolProvince" class="control-label"></label>
                        <input asp-for="SchoolProvince" class="form-control" />
                        <span asp-validation-for="SchoolProvince" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <hr />

            <h3>Indirizzo personale</h3>

            <div class="form-group">
                <label asp-for="PersonalAddress" class="control-label"></label>
                <input asp-for="PersonalAddress" class="form-control" />
                <span asp-validation-for="PersonalAddress" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="col-sm-3">
                    <div class="form-group">
                        <label asp-for="PersonalCap" class="control-label"></label>
                        <input asp-for="PersonalCap" class="form-control" />
                        <span asp-validation-for="PersonalCap" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="form-group">
                        <label asp-for="PersonalCity" class="control-label"></label>
                        <input asp-for="PersonalCity" class="form-control" />
                        <span asp-validation-for="PersonalCity" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label asp-for="PersonalProvince" class="control-label"></label>
                        <input asp-for="PersonalProvince" class="form-control" />
                        <span asp-validation-for="PersonalProvince" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <hr />

            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <button id="submit" type="submit" value="submit" class="btn btn-primary btn-block">Registrati!</button>
        </form>
    </div>

</div>

src/Web/Web/Views/Dashboard/PignaRegistrationConfirmation.cshtml
@{
    Layout = "Main";
    ViewData["Title"] = "Registrazione Pigna";
}

<div class="container">
    <h1 class="text-center">Registrazione Pigna</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        <p>◀&nbsp;@Html.ActionLink("Torna al pannello di controllo", "Index")</p>

        <p>
            La registrazione è andata a buon fine! Grazie. 👍
        </p>

    </div>

</div>

src/Web/Web/Views/Dashboard/Status.cshtml
@using CodeMooc.Web
@using CodeMooc.Web.Model
@model DashboardStatusViewModel
@{
    Layout = "Main";
    ViewData["Title"] = "Stato";
}

<div class="container">
    <h1 class="text-center">Stato</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        <p>◀&nbsp;@Html.ActionLink("Torna al pannello di controllo", "Index")</p>

        <h2>Indirizzi e-mail</h2>

        <p>Indirizzi e-mail associati al tuo account:</p>
        <ul>
            @foreach (var e in Model.Emails) {
                <li>
                    @e.Address @if (e.IsPrimary) {
                    <span>(Primario)</span>
                }
                </li>
            }
        </ul>

        <h2>Registrazione</h2>

        @if (Model.IsRegistrationConfirmed) {
            <p>La tua registrazione è stata confermata correttamente.</p>
        }
        else {
            <p class="warning">La tua registrazione non è confermata!</p>
            <p class="help">
                Verifica di aver ricevuto una e-mail di conferma dall'indirizzo <i>@Model.ConfirmationEmailAddress</i> (controlla anche nella cartella dello spam).
                Se così non fosse, contatta <i>associazione@codemooc.net</i> scrivendo un'e-mail dall'indirizzo <i>@Model.PrimaryEmail.Address</i>.
            </p>
        }

        <h2>Badge e iscrizione</h2>

        @if (Model.Badges.Count == 0) {
            <p><i>Nessun badge emesso.</i></p>
        }
        else {
            <ul>
                @foreach (var badge in Model.Badges) {
                    <li>
                        @badge.Type.GetName(badge.Year.Year) (@Html.ActionLink("vedi", "ShowEvidenceYear", "Badge", new { type = badge.Type.GetPathToken(), year = badge.Year.Year, token = badge.EvidenceToken }, null))
                    </li>
                }
            </ul>
        }

        @if(Model.IsAssociateForCurrentYear) {
            <p>Risulti correttamente iscritto/a all'associazione CodeMOOC.net per il corrente anno. Grazie!</p>
        }

    <p>
        <i>Nota:</i> sono richieste fino a 24&nbsp;ore per verificare la corrispondenza tra donazioni registrate tramite iscrizione al servizio e <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">crowdfunding</a>, con relativo aggiornamento dello stato da socio ed emissione dei badge.
    </p>

    </div>

</div>

src/Web/Web/Views/Dashboard/Upload.cshtml
@using CodeMooc.Web.Model
@model DashboardUploadViewModel
@{
    Layout = "Main";
    ViewData["Title"] = "Raccolta curricula";
}

<div class="container">
    <h1 class="text-center">Raccolta curricula</h1>

    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3">

        <p>◀&nbsp;@Html.ActionLink("Torna al pannello di controllo", "Index")</p>

        <p>
            CodeMOOC.net sta sviluppando una <b>rete di competenze ed esperienze</b>,  una via di mezzo tra una raccolta di curricula ed un social network.
            Questo strumento verrà <b>sviluppato su misura</b>, in modo che rappresenti al meglio la rete degli associati, le loro esperienze professionali e le relazioni che le valorizzano.
        </p>

        <p>
            Tramite questo modulo raccoglieremo i curricula degli associati, in modo da usarli come base di dati reale attorno alla quale costruire lo strumento.
        </p>

        @if (!Model.IsAssociateForCurrentYear) {
            <div class="form-error">
                Questo modulo è disponibile soltanto per soci dell'associazione CodeMOOC.
                Unisciti alla <a href="https://www.produzionidalbasso.com/project/codemooc-net-2021/">campagna di crowdfunding</a> per diventare socio.
            </div>
        }
        else {
            <h2>Profilo utente</h2>

            <p>
                Usa questo modulo per caricare un'immagine di profilo che ti rappresenti sulla rete di associati CodeMOOC.net.
                Utilizza immagini di formato quadrato.
            </p>

            @if (Model.ProfilePictureFilename != null) {
                <p class="text-center">
                    <img src="~/uploads/profiles/@Model.ProfilePictureFilename" alt="Profilo utente" class="avatar img-fluid" />
                </p>
            }

            <form asp-controller="Dashboard" asp-action="ProcessCvUpload" method="post" enctype="multipart/form-data" class="form-horizontal" role="form" asp-antiforgery="true">
                <div>
                    <div class="form-group">
                        <label for="profilePic">Immagine profilo:</label>
                        <input name="profilePic" type="file" class="input-form-control" accept="image/*" />
                    </div>

                    <button id="submit" type="submit" value="submit" class="btn btn-primary btn-block">Carica immagine profilo</button>
                </div>
            </form>

            <h2>Curriculum</h2>

            <p>
                Usa questo modulo per caricare il tuo curriculum in formato EuroPass: utilizza l'<a href="https://europass.cedefop.europa.eu/it/documents/curriculum-vitae">editor online</a> per creare il documento e trasmettilo qui in formato PDF.
            </p>

            @if (Model.CurriculumFilename != null) {
                <p>
                    <b>Il tuo curriculum è stato caricato correttamente!</b><br />
                    File attuale: <a href="~/uploads/curricula/@Model.CurriculumFilename">@Model.CurriculumFilename</a>.
                </p>
            }

            <form asp-controller="Dashboard" asp-action="ProcessCvUpload" method="post" enctype="multipart/form-data" class="form-horizontal" role="form" asp-antiforgery="true">
                <div>
                    <div class="form-group">
                        <label for="curriculum">Curriculum:</label>
                        <input name="curriculum" type="file" class="input-form-control" accept="application/pdf" />
                    </div>

                    @if (Model.CurriculumFailure == DashboardUploadViewModel.CurriculumUploadFailure.WrongExtension) {
                        <div class="form-error">
                            Il curriculum deve essere in formato PDF.
                        </div>
                    }

                    <button id="submit" type="submit" value="submit" class="btn btn-primary btn-block">Carica curriculum</button>
                </div>
            </form>
        }

    </div>

</div>